# fly.toml app configuration file for Laravel fitness backend
app = "fitness-pro-backend"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile.prod"

[deploy]
  release_command = "php artisan migrate --force"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "database"
  CACHE_DRIVER = "database"
  QUEUE_CONNECTION = "database"

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    tls_skip_verify = false

[mounts]
  source = "fitness_storage"
  destination = "/var/www/html/storage"

[[statics]]
  guest_path = "/var/www/html/public"
  url_prefix = "/static"