app = "fitness-backend-api-v2"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"

[env]
  APP_ENV = "production"
  APP_DEBUG = "false"
  LOG_CHANNEL = "stderr"
  SESSION_DRIVER = "database"
  CACHE_DRIVER = "database"
  QUEUE_CONNECTION = "database"
  DB_CONNECTION = "sqlite"
  FILESYSTEM_DISK = "local"

[http_service]
  internal_port = 80
  force_https = true

[deploy]
  release_command = "php artisan migrate --force"
  strategy = "immediate"