app = "fitness-pro-backend"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  SESSION_DRIVER = "database"
  CACHE_DRIVER = "database"

[http_service]
  internal_port = 80
  force_https = true

[deploy]
  release_command = "php artisan migrate --force"